### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by henrist** [cybernetisk/internsystem#105]
Sette opp en `.editorconfig` for å ha konsekvent formattering.

http://editorconfig.org/

**Comment by dizzi90** [comment]
@henrist  Sjekk om den jeg la til i pull requesten er akseptabel som et utgangspunkt. Jeg tror ikke det så viktig hva normene er i begynnelsen. Bare man har en og er konsekvent så er det relativt lett å endre senere om noe annet er mer fornuftig.
