### ISSUE TITLE
Tregt endepunkt api/cal/upcoming

### ISSUE THREAD

**Issue by matsasc** [cybernetisk/internsystem#164]
Det tar ekstremt lang tid å hente events fra endepunktet.

**Comment by kamnxt** [comment]
Ser ut som problemet er på in.cyb.no, får ofte ca 10-30x lavere loading time (ca 400ms vs ca 4000ms - 12000ms) når jeg kjører internsystem lokalt... Kan prøve å implementere caching

**Comment by adriah** [comment]
@kamnxt er det kun dette endepunktet som er så tregt, eller er det generelt sett alle kall?

Ser litt på å få flyttet alt over til en annen løsning.

**Comment by matsasc** [comment]
Burde være delvis fikset med å cache det endepunktet i databasen
