### ISSUE TITLE
automatisk oppdatere sympalister

### ISSUE THREAD

**Issue by matsasc** [cybernetisk/internsystem#84]
Hadde en snakk med en av postmasterene på uio før sommeren.

Er mulig å hente brukere for sympalistene våre via txt filer på nett. Kan være en idé å implementere en måte å hente ut lister for det i nye garm.

**Comment by henrist** [comment]
Burde vi ikke nesten ha det andre veien? At Sympa oppdaterer seg på bakgrunn av Garm?

Ser for meg at man enklere holder Garm oppdatert enn Sympa :p

**Comment by matsasc** [comment]
Var vel det jeg egentlig mente, Sympa kan hente ned tekstfiler fra nett og legge inn folk i riktige sympalister

**Comment by henrist** [comment]
Ah, bra. Jeg leste det som motsatt.

Men ja. Oppdatere Sympa automatisk med data fra Garm. Hadde vært kjekt.

Og hvis vi bare kan eksponere en URL med data som Sympa kan hente hadde jo det vært supert. Men jeg mener å huske at det er lite pålitelig, og at Sympa i praksis krever at URL-en aldri er utilgjengelig?

**Comment by matsasc** [comment]
Ja, den krever at det er god oppetid på listene.

**Comment by matsasc** [comment]
Er jo 2 muligheter der, enten stole på scaleway vmen vår, eller mellomlagre den på cyb brukeren og gi dem linkene fra den.

**Comment by henrist** [comment]
I så fall kan det godt hende det er enklere å synke mot en fil på CYB-brukeren f.eks. Også at Sympa sourcer den i stedet for?

**Comment by matsasc** [comment]
Da kan man jo gjøre det så enkelt som å skrive et lite python script for å hente ut de listene, kjøre de i cron på cyb brukeren. Så slipper man å rote med cron i docker kontainerene. De kjører vel ikke crond selv, så man måtte vel eventuelt gått gjennom hosten.

**Comment by henrist** [comment]
Godt poeng, basicly bare lage en cache for Sympa som polles fra CYB-brukeren. Støtter den!

**Comment by matsasc** [comment]
Lukker denne da vi har sluttet å bruke Sympa
